name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy -snowflake-changes-job:
    runs-on: ubuntu-latest
    environment: DEV

  name: Run a script
  run:
    echo "I am running a job in the DEV environment"
